### PR TITLE
Create UTS namespace for pod by default

### PR DESCRIPTION
**Pull request by sashayakovtseva**

### CODE REVIEW

**Comment by cclerget** [comment]
@sashayakovtseva Looking at the source tree, maybe I'm missing something, I don't see where POD hostname is set to host default if not provided

**Comment by sashayakovtseva** [comment]
@cclerget It is not set anywhere because new UTS namespace inherits hostname of the ancestor, i.e host. 
Only question I have now is whether `/etc/hostname` file should be mounted to container from host in that case.

**Comment by cclerget** [comment]
Yes I know but I mean where you get the host hostname and set it in POD configuration within the code , because k8s api `GetHostname` returns an empty string if not set in provided configuration

I would take same path as with custom hostname by creating a dedicated file by POD not a bind mount, since its a dedicated UTS namespace, if a container process change hostname for some reasons, it won't affect host and won't hurt program by refusing access with a read-only error.

**Comment by sashayakovtseva** [comment]
@cclerget I don't set it to host's hostname explicitly, just leave an empty hostname in oci config.json. Should it be filled anyway?

**Comment by cclerget** [comment]
You need to get it to set hostname file content anyway so yes set it explicitly, that should not imply to many code and you could reuse same code path, and that doesn't matter on runtime side since it will blindly set hostname according to configuration

**Pull request merged**
